server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
    access:
      default: unrestricted
spring:
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
              predicates:
                - name: Path
                  args:
                    pattern: "'/api/' + serviceId + '/**'"
              filters:
                - name: RewritePath
                  args:
                    regexp: "'/api/' + serviceId + '/(?<remaining>.*)'"
                    replacement: "{metadata.get('contextPath') != null ? metadata.get('contextPath') : ''} + '/${remaining}'"